add exclude filtering
calebccff/SUTimetableApi pull request #2
Opened 2021-09-21 12:45 UTC by MathematicalDessert

This resolves #1.

2021-09-21 12:52 UTC, calebccff requested changes
pog PR thanks PK

2021-09-21 12:52 UTC, calebccff commented on .vscode/settings.json
> +    "python.pythonPath": "C:\\Python39\\python.exe"
lol nice, probably should drop .vscode from git.

2021-09-21 12:52 UTC, calebccff commented on main.py
> +    excludeList = request.args.get('exclude')
Can you update the readme to reflect the API changes?

2021-09-21 12:52 UTC, calebccff commented on main.py
> +    # g is now optional
Do we need G anymore? Can just drop it entirely.

2021-09-21 12:52 UTC, calebccff commented on main.py
> +        if g != None:
Dropping g lets us drop this stuff to.

2021-09-21 13:15 UTC, MathematicalDessert commented on .vscode/settings.json
> +    "python.pythonPath": "C:\\Python39\\python.exe"
Yeah, I was going to add it to the .gitignore...I guess I will

2021-09-21 13:18 UTC, MathematicalDessert commented on main.py
> +    # g is now optional
We could allow for first and second year students to use the API too, and by the looks of it the groupings still exist. Lmk what you think

![image](https://user-images.githubusercontent.com/28831011/134177568-9cfdf295-99da-4ec2-8c53-4aec9c13de0e.png)

2021-09-21 13:18 UTC, MathematicalDessert commented on main.py
> +        if g != None:
See above.

2021-09-26 22:32 UTC, calebccff commented on main.py
> +    # g is now optional
Sure

2021-09-26 22:33 UTC, calebccff commented
Sweet!

2021-09-26 22:34 UTC, merged